### ISSUE TITLE
libdislocator not work as expected when target program use posix_memalign

### ISSUE THREAD

**Issue by ManhNDd** [google/AFL#40]
I fuzzed OpenJPEG (https://github.com/uclouvain/openjpeg) with AFL and used libdislocator.so. Because OpenJPEG uses **posix_memalign** in its code, **malloc** of libc is called (not **malloc** in libdislocator.so). Later, **free** of libdislocator.so is called to free the pointer returned from **malloc** in libc, so triggers **_"bad allocator canary on free()"_** => false crash report.

**Reproduce**
Command to build OpenJPEG:
```
CC=gcc CXX=g++ cmake .. -DCMAKE_C_FLAGS="-std=c99 -O0 -ggdb -Wno-error -Wdeclaration-after-statement" -DBUILD_THIRDPARTY:BOOL=ON
```
Jp2_crash file: https://drive.google.com/open?id=11_u0WKKK71qMTzRLmjJAILs3QIQavlBF
Run opj_decompress with libdislocator:
```
root@manh-ubuntu16:~/fuzz/fuzz_openjpeg# LD_PRELOAD=/root/fuzz/afl-2.52b/libdislocator/libdislocator.so ./openjpeg/build-noafl/bin/opj_decompress -i ./jp2_crash -o im.pgm

===========================================
The extension of this file is incorrect.
FOUND rash. SHOULD BE .jp2
===========================================

[INFO] Start to read j2k main header (123).
[ERROR] Unknown progression order in COD marker
[INFO] Main header has been correctly decoded.
[INFO] No decoded area parameters, set the decoded area to the whole image
[INFO] Header of tile 1 / 1 has been read.
[ERROR] Failed to decode.
[ERROR] Failed to decode tile 1/1
[ERROR] Failed to decode the codestream in the JP2 file
ERROR -> opj_decompress: failed to decode image!
*** [AFL] bad allocator canary on free() ***
Aborted (core dumped)
```
**Analysis**
Run in gdb:
```
root@manh-ubuntu16:~/fuzz/fuzz_openjpeg# gdb ./openjpeg/build-noafl/bin/opj_decompress
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./openjpeg/build-noafl/bin/opj_decompress...done.
(gdb) set environment LD_PRELOAD /root/fuzz/afl-2.52b/libdislocator/libdislocator.so
(gdb) watch *0x732008
Hardware watchpoint 2: *0x732008
(gdb) r
Starting program: /root/fuzz/fuzz_openjpeg/openjpeg/build-noafl/bin/opj_decompress -i ./jp2_crash -o im.pgm
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

===========================================
The extension of this file is incorrect.
FOUND rash. SHOULD BE .jp2
===========================================

[INFO] Start to read j2k main header (123).
[ERROR] Unknown progression order in COD marker
[INFO] Main header has been correctly decoded.
[INFO] No decoded area parameters, set the decoded area to the whole image
[INFO] Header of tile 1 / 1 has been read.

Hardware watchpoint 2: *0x732008

Old value = <unreadable>
New value = 139265
sysmalloc (nb=nb@entry=7664, av=av@entry=0x7ffff7228b20 <main_arena>)
    at malloc.c:2679
2679	malloc.c: No such file or directory.
(gdb) bt
#0  sysmalloc (nb=nb@entry=7664, av=av@entry=0x7ffff7228b20 <main_arena>)
    at malloc.c:2679
#1  0x00007ffff6ee6743 in _int_malloc (
    av=av@entry=0x7ffff7228b20 <main_arena>, bytes=bytes@entry=7656)
    at malloc.c:3827
#2  0x00007ffff6ee9898 in __GI___libc_malloc (bytes=7656) at malloc.c:2913
#3  malloc_hook_ini (sz=7656, caller=<optimized out>) at hooks.c:32
#4  0x00007ffff6eeb7ae in _mid_memalign (address=<optimized out>, bytes=7656, 
    alignment=<optimized out>) at malloc.c:3083
#5  __posix_memalign (memptr=0x7fffffff8e90, alignment=<optimized out>, 
    size=7656) at malloc.c:5028
#6  0x00007ffff79c16a7 in opj_aligned_alloc_n (alignment=16, size=7656)
    at /root/fuzz/fuzz_openjpeg/openjpeg/src/lib/openjp2/opj_malloc.c:61
#7  0x00007ffff79c1845 in opj_aligned_malloc (size=7656)
    at /root/fuzz/fuzz_openjpeg/openjpeg/src/lib/openjp2/opj_malloc.c:209
#8  0x00007ffff799423e in opj_image_data_alloc (size=7656)
    at /root/fuzz/fuzz_openjpeg/openjpeg/src/lib/openjp2/openjpeg.c:1056
#9  0x00007ffff79bb680 in opj_alloc_tile_component_data (
    l_tilec=0x7ffff7e9deb0)
    at /root/fuzz/fuzz_openjpeg/openjpeg/src/lib/openjp2/tcd.c:694
#10 0x00007ffff79bdac4 in opj_tcd_decode_tile (p_tcd=0x7ffff7ea3f98, 
    win_x0=16, win_y0=0, win_x1=49, win_y1=58, numcomps_to_decode=0, 
    comps_indices=0x0, 
    p_src=0x7ffff7e79eb5 "ϴ\024\001\337{\030\205\200\200\301\363\204\237\200\064\037P(\f\003\300\325\017\307\313m\264z\017\373jkC\200\200\307\312\"}A\320\371D\200\030\251\070=\303>\240\252 0$]\224x\247;\202\061\227\242B\235\025\373\353\"\241\345f╀\300\371\002", p_max_length=329, p_tile_no=0, 
    p_cstr_index=0x7ffff7fddfc8, p_manager=0x7ffff7fe8fa8)
    at /root/fuzz/fuzz_openjpeg/openjpeg/src/lib/openjp2/tcd.c:1530
#11 0x00007ffff79828f6 in opj_j2k_decode_tile (p_j2k=0x7ffff7fe4eb0, 
    p_tile_index=0, p_data=0x0, p_data_size=0, p_stream=0x7ffff7fedf88, 
    p_manager=0x7ffff7fe8fa8)
    at /root/fuzz/fuzz_openjpeg/openjpeg/src/lib/openjp2/j2k.c:8932
#12 0x00007ffff798731e in opj_j2k_decode_tiles (p_j2k=0x7ffff7fe4eb0, 
    p_stream=0x7ffff7fedf88, p_manager=0x7ffff7fe8fa8)
    at /root/fuzz/fuzz_openjpeg/openjpeg/src/lib/openjp2/j2k.c:10719
#13 0x00007ffff7980904 in opj_j2k_exec (p_j2k=0x7ffff7fe4eb0, 
    p_procedure_list=0x7ffff7fd5ff0, p_stream=0x7ffff7fedf88, 
    p_manager=0x7ffff7fe8fa8)
    at /root/fuzz/fuzz_openjpeg/openjpeg/src/lib/openjp2/j2k.c:8090
#14 0x00007ffff7987eba in opj_j2k_decode (p_j2k=0x7ffff7fe4eb0, 
    p_stream=0x7ffff7fedf88, p_image=0x7ffff7e9bfd0, p_manager=0x7ffff7fe8fa8)
    at /root/fuzz/fuzz_openjpeg/openjpeg/src/lib/openjp2/j2k.c:11014
#15 0x00007ffff798d2b9 in opj_jp2_decode (jp2=0x7ffff7fe6f50, 
    p_stream=0x7ffff7fedf88, p_image=0x7ffff7e9bfd0, p_manager=0x7ffff7fe8fa8)
    at /root/fuzz/fuzz_openjpeg/openjpeg/src/lib/openjp2/jp2.c:1603
---Type <return> to continue, or q <return> to quit---
#16 0x00007ffff799361d in opj_decode (p_codec=0x7ffff7fe8f48, 
    p_stream=0x7ffff7fedf88, p_image=0x7ffff7e9bfd0)
    at /root/fuzz/fuzz_openjpeg/openjpeg/src/lib/openjp2/openjpeg.c:483
#17 0x0000000000413d87 in main (argc=5, argv=0x7fffffffe428)
    at /root/fuzz/fuzz_openjpeg/openjpeg/src/bin/jp2/opj_decompress.c:1542
(gdb) c
Continuing.

Hardware watchpoint 2: *0x732008

Old value = 139265
New value = 7665
sysmalloc (nb=nb@entry=7664, av=av@entry=0x7ffff7228b20 <main_arena>)
    at malloc.c:2738
2738	in malloc.c
(gdb) c
Continuing.
[ERROR] Failed to decode.
[ERROR] Failed to decode tile 1/1
[ERROR] Failed to decode the codestream in the JP2 file
ERROR -> opj_decompress: failed to decode image!
*** [AFL] bad allocator canary on free() ***

Program received signal SIGABRT, Aborted.
0x00007ffff6e99428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6e99428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff6e9b02a in __GI_abort () at abort.c:89
#2  0x00007ffff7bd570a in free (ptr=<optimized out>) at libdislocator.so.c:221
#3  0x00007ffff79c18cc in opj_aligned_free (ptr=0x732010)
    at /root/fuzz/fuzz_openjpeg/openjpeg/src/lib/openjp2/opj_malloc.c:228
#4  0x00007ffff7994260 in opj_image_data_free (ptr=0x732010)
    at /root/fuzz/fuzz_openjpeg/openjpeg/src/lib/openjp2/openjpeg.c:1064
#5  0x00007ffff79be77b in opj_tcd_free_tile (p_tcd=0x7ffff7ea3f98)
    at /root/fuzz/fuzz_openjpeg/openjpeg/src/lib/openjp2/tcd.c:1891
#6  0x00007ffff79bb5ef in opj_tcd_destroy (tcd=0x7ffff7ea3f98)
    at /root/fuzz/fuzz_openjpeg/openjpeg/src/lib/openjp2/tcd.c:676
#7  0x00007ffff7981082 in opj_j2k_destroy (p_j2k=0x7ffff7fe4eb0)
    at /root/fuzz/fuzz_openjpeg/openjpeg/src/lib/openjp2/j2k.c:8306
#8  0x00007ffff79902e2 in opj_jp2_destroy (jp2=0x7ffff7fe6f50)
    at /root/fuzz/fuzz_openjpeg/openjpeg/src/lib/openjp2/jp2.c:3012
#9  0x00007ffff7993f5b in opj_destroy_codec (p_codec=0x7ffff7fe8f48)
    at /root/fuzz/fuzz_openjpeg/openjpeg/src/lib/openjp2/openjpeg.c:927
#10 0x0000000000413dd9 in main (argc=5, argv=0x7fffffffe428)
    at /root/fuzz/fuzz_openjpeg/openjpeg/src/bin/jp2/opj_decompress.c:1545
```
As you can see, a watch on 0x732008 shows that __posix_memalign is called, which then called malloc in libc, return a pointer of 0x732010. Later, free of libdislocator is called to free the pointer 0x732010 => **_"[AFL] bad allocator canary on free()"_** => false report.

**Comment by jonathanmetzman** [comment]
We'd accept a patch for `posix_memalign/memalign` if you want to do one.
I can try taking a look myself but I won't make any guarantees since I myself use ASAN and don't use libdislocator. I think implementing this correctly is nontrivial.

**Comment by jonathanmetzman** [comment]
Actually, implementing the dirtry solution of simply adding the alignment to the requested size and then ensuring alignment on the returned pointer could potentially work. Need to think about this.

**Comment by vanhauser-thc** [comment]
we have that in afl++, just copy+paste :)
